spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tdd
    password: test1234
    url: jdbc:mysql://localhost:3306/tddschema?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
